### ISSUE TITLE
Tracking Issue: Parser and Grammar Support for Language Features

### ISSUE THREAD

**Issue by keks** [sspverif/sspverif#2]
The language has a could of features that the parsing grammar does not yet support:
-  [x] Statements:
  - [x] table assignments
- [ ] Expressions:
  - [ ] Arithmetic
     - [x] Add Sub Mul Div
     - [ ] ~Pow Mod~
     - [x] Not ~Neg Inv~
     - [x] And Or Xor
  - [x] Literals
    - [x] integers
    - [x] strings
    - [x] booleans
  - [x] Lists
  - [ ] ~Sets~
  - [ ] ~Set/List Arithmetic~
    - [ ] ~Sum Prod~
    - [ ] ~Any All~
    - [ ] ~Union Cut SetDiff~
    - [ ] ~Concat~

Support needs to be added both to the grammar and to the parser. For a bunch of these we probably also don't have SMT writer support yet.
